"""empty message

Revision ID: bdee798b99bd
Revises: 
Create Date: 2024-03-19 15:00:51.395853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdee798b99bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customerName', sa.String(length=150), nullable=False),
    sa.Column('custAddress', sa.String(length=150), nullable=True),
    sa.Column('custNo', sa.String(length=150), nullable=True),
    sa.Column('invoiceNo', sa.String(length=150), nullable=True),
    sa.Column('serArea', sa.String(length=150), nullable=True),
    sa.Column('instruct', sa.String(length=150), nullable=True),
    sa.Column('service', sa.String(length=150), nullable=True),
    sa.Column('appDate', sa.String(length=150), nullable=True),
    sa.Column('timeIn', sa.String(length=150), nullable=True),
    sa.Column('timeOut', sa.String(length=150), nullable=True),
    sa.Column('temp', sa.String(length=150), nullable=True),
    sa.Column('windDir', sa.String(length=150), nullable=True),
    sa.Column('windSpeed', sa.String(length=150), nullable=True),
    sa.Column('lic', sa.String(length=150), nullable=True),
    sa.Column('sqft', sa.String(length=150), nullable=True),
    sa.Column('sprayer', sa.String(length=150), nullable=True),
    sa.Column('rate', sa.String(length=150), nullable=True),
    sa.Column('target', sa.String(length=150), nullable=True),
    sa.Column('product', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('ticket')
    # ### end Alembic commands ###
